<?php
/**
 * ScanBinariesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\StorageApiSdk
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\StorageApiSdk\Client\Api;

use \Softonic\StorageApiSdk\Configuration;
use \Softonic\StorageApiSdk\ApiClient;
use \Softonic\StorageApiSdk\ApiException;
use \Softonic\StorageApiSdk\ObjectSerializer;

/**
 * ScanBinariesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\StorageApiSdk
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScanBinariesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for createScanBinary
     *
     * Creates a new ScanBinary
     *
     */
    public function test_createScanBinary() {

    }
    
    /**
     * Test case for deleteScanBinary
     *
     * Deletes a ScanBinary
     *
     */
    public function test_deleteScanBinary() {

    }
    
    /**
     * Test case for findScanBinary
     *
     * List of ScanBinarys
     *
     */
    public function test_findScanBinary() {

    }
    
    /**
     * Test case for readScanBinary
     *
     * Fetches a single ScanBinary
     *
     */
    public function test_readScanBinary() {

    }
    
    /**
     * Test case for updateScanBinary
     *
     * Partially updates a ScanBinary
     *
     */
    public function test_updateScanBinary() {

    }
    
}
