<?php
/**
 * FileCdnDestination
 *
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\StorageApiSdk
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Restful API based on CoreAPI technology
 *
 * Add your description here
 *
 * OpenAPI spec version: 2.0.87-7
 * Contact: XXXXXXXXX@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Softonic\StorageApiSdk\Model;

use \ArrayAccess;

/**
 * FileCdnDestination Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Softonic\StorageApiSdk
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FileCdnDestination implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'FileCdnDestination';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'id_files' => 'string',
        'id_cdn_destinations' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'id_files' => 'id_files',
        'id_cdn_destinations' => 'id_cdn_destinations'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'id_files' => 'setIdFiles',
        'id_cdn_destinations' => 'setIdCdnDestinations'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'id_files' => 'getIdFiles',
        'id_cdn_destinations' => 'getIdCdnDestinations'
    );

    public static function getters()
    {
        return self::$getters;
    }

    const ID_CDN_DESTINATIONS_PROGRAM_PRIVATE = 'program_private';
    const ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_STAGING = 'program_private_staging';
    const ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_INTEGRATION = 'program_private_integration';
    const ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_DEVELOPMENT = 'program_private_development';
    const ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_ADD_NEW_CDN = 'program_private_add_new_cdn';
    const ID_CDN_DESTINATIONS_IMAGES_PUBLIC = 'images_public';
    const ID_CDN_DESTINATIONS_IMAGES_PUBLIC_STAGING = 'images_public_staging';
    const ID_CDN_DESTINATIONS_IMAGES_PUBLIC_INTEGRATION = 'images_public_integration';
    const ID_CDN_DESTINATIONS_IMAGES_PUBLIC_DEVELOPMENT = 'images_public_development';
    const ID_CDN_DESTINATIONS_RPM_PROTECTED = 'rpm_protected';
    const ID_CDN_DESTINATIONS_REPORTS_PUBLIC = 'reports_public';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getIdCdnDestinationsAllowableValues()
    {
        return [
            self::ID_CDN_DESTINATIONS_PROGRAM_PRIVATE,
            self::ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_STAGING,
            self::ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_INTEGRATION,
            self::ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_DEVELOPMENT,
            self::ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_ADD_NEW_CDN,
            self::ID_CDN_DESTINATIONS_IMAGES_PUBLIC,
            self::ID_CDN_DESTINATIONS_IMAGES_PUBLIC_STAGING,
            self::ID_CDN_DESTINATIONS_IMAGES_PUBLIC_INTEGRATION,
            self::ID_CDN_DESTINATIONS_IMAGES_PUBLIC_DEVELOPMENT,
            self::ID_CDN_DESTINATIONS_RPM_PROTECTED,
            self::ID_CDN_DESTINATIONS_REPORTS_PUBLIC,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id_files'] = isset($data['id_files']) ? $data['id_files'] : null;
        $this->container['id_cdn_destinations'] = isset($data['id_cdn_destinations']) ? $data['id_cdn_destinations'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['id_files'] === null) {
            $invalid_properties[] = "'id_files' can't be null";
        }
        if ((strlen($this->container['id_files']) > 40)) {
            $invalid_properties[] = "invalid value for 'id_files', the character length must be smaller than or equal to 40.";
        }

        if ((strlen($this->container['id_files']) < 40)) {
            $invalid_properties[] = "invalid value for 'id_files', the character length must be bigger than or equal to 40.";
        }

        if ($this->container['id_cdn_destinations'] === null) {
            $invalid_properties[] = "'id_cdn_destinations' can't be null";
        }
        $allowed_values = array("program_private", "program_private_staging", "program_private_integration", "program_private_development", "program_private_add_new_cdn", "images_public", "images_public_staging", "images_public_integration", "images_public_development", "rpm_protected", "reports_public");
        if (!in_array($this->container['id_cdn_destinations'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'id_cdn_destinations', must be one of #{allowed_values}.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['id_files'] === null) {
            return false;
        }
        if (strlen($this->container['id_files']) > 40) {
            return false;
        }
        if (strlen($this->container['id_files']) < 40) {
            return false;
        }
        if ($this->container['id_cdn_destinations'] === null) {
            return false;
        }
        $allowed_values = array("program_private", "program_private_staging", "program_private_integration", "program_private_development", "program_private_add_new_cdn", "images_public", "images_public_staging", "images_public_integration", "images_public_development", "rpm_protected", "reports_public");
        if (!in_array($this->container['id_cdn_destinations'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets id_files
     * @return string
     */
    public function getIdFiles()
    {
        return $this->container['id_files'];
    }

    /**
     * Sets id_files
     * @param string $id_files SHA-1 hash of the file
     * @return $this
     */
    public function setIdFiles($id_files)
    {
        if (strlen($id_files) > 40) {
            throw new \InvalidArgumentException('invalid length for $id_files when calling FileCdnDestination., must be smaller than or equal to 40.');
        }
        if (strlen($id_files) < 40) {
            throw new \InvalidArgumentException('invalid length for $id_files when calling FileCdnDestination., must be bigger than or equal to 40.');
        }
        $this->container['id_files'] = $id_files;

        return $this;
    }

    /**
     * Gets id_cdn_destinations
     * @return string
     */
    public function getIdCdnDestinations()
    {
        return $this->container['id_cdn_destinations'];
    }

    /**
     * Sets id_cdn_destinations
     * @param string $id_cdn_destinations CDN destination where the file is uploaded
     * @return $this
     */
    public function setIdCdnDestinations($id_cdn_destinations)
    {
        $allowed_values = array('program_private', 'program_private_staging', 'program_private_integration', 'program_private_development', 'program_private_add_new_cdn', 'images_public', 'images_public_staging', 'images_public_integration', 'images_public_development', 'rpm_protected', 'reports_public');
        if (!in_array($id_cdn_destinations, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'id_cdn_destinations', must be one of 'program_private', 'program_private_staging', 'program_private_integration', 'program_private_development', 'program_private_add_new_cdn', 'images_public', 'images_public_staging', 'images_public_integration', 'images_public_development', 'rpm_protected', 'reports_public'");
        }
        $this->container['id_cdn_destinations'] = $id_cdn_destinations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Softonic\StorageApiSdk\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Softonic\StorageApiSdk\ObjectSerializer::sanitizeForSerialization($this));
    }
}


