<?php
namespace Softonic\StorageApiInstance\Sdk\Exceptions;

/**
 * Resource not found exception.
 *
 * Generated by SDK generator.
 *
 * @package Softonic\StorageApiInstance\Sdk
 * @author Kyryl Sablin <kyryl.sablin@softonic.com>
 */
class NotFoundException extends ApiException
{
}

