<?php
/**
 * FileTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\StorageApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Restful API based on CoreAPI technology
 *
 * Add your description here
 *
 * OpenAPI spec version: 2.0.92-37
 * Contact: XXXXXXXXX@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Softonic\StorageApiSdk;

/**
 * FileTest Class Doc Comment
 *
 * @category    Class */
// * @description File
/**
 * @package     Softonic\StorageApiSdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FileTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "File"
     */
    public function testFile()
    {
    }

    /**
     * Test attribute "id_files"
     */
    public function testPropertyIdFiles()
    {
    }

    /**
     * Test attribute "sha256_hash"
     */
    public function testPropertySha256Hash()
    {
    }

    /**
     * Test attribute "filename"
     */
    public function testPropertyFilename()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }
}
