<?php
/**
 * FileCdnDestinationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\StorageApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Storage API
 *
 * Saves binary files in CDN providers for allowing later downloads
 *
 * OpenAPI spec version: 2.31.0
 * Contact: admin@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Softonic\StorageApiSdk;

/**
 * FileCdnDestinationTest Class Doc Comment
 *
 * @category    Class */
// * @description FileCdnDestination
/**
 * @package     Softonic\StorageApiSdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FileCdnDestinationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FileCdnDestination"
     */
    public function testFileCdnDestination()
    {
    }

    /**
     * Test attribute "id_files"
     */
    public function testPropertyIdFiles()
    {
    }

    /**
     * Test attribute "id_cdn_destinations"
     */
    public function testPropertyIdCdnDestinations()
    {
    }
}
