<?php
/**
 * File
 *
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\StorageApiSdk
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Softonic\StorageApiSdk\Client\Model;

use \ArrayAccess;
/**
 * File Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Softonic\StorageApiSdk
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class File implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id_files' => 'string',
        'sha256_hash' => 'string',
        'filename' => 'string',
        'size' => 'int'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id_files' => 'id_files',
        'sha256_hash' => 'sha256_hash',
        'filename' => 'filename',
        'size' => 'size'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id_files' => 'setIdFiles',
        'sha256_hash' => 'setSha256Hash',
        'filename' => 'setFilename',
        'size' => 'setSize'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id_files' => 'getIdFiles',
        'sha256_hash' => 'getSha256Hash',
        'filename' => 'getFilename',
        'size' => 'getSize'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $id_files SHA-1 hash of the file
      * @var string
      */
    protected $id_files;
    
    /**
      * $sha256_hash SHA-256 hash of the file
      * @var string
      */
    protected $sha256_hash;
    
    /**
      * $filename Name of the file
      * @var string
      */
    protected $filename;
    
    /**
      * $size Size of the file
      * @var int
      */
    protected $size;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->id_files = $data["id_files"];
            $this->sha256_hash = $data["sha256_hash"];
            $this->filename = $data["filename"];
            $this->size = $data["size"];
        }
    }
    
    /**
     * Gets id_files
     * @return string
     */
    public function getIdFiles()
    {
        return $this->id_files;
    }
  
    /**
     * Sets id_files
     * @param string $id_files SHA-1 hash of the file
     * @return $this
     */
    public function setIdFiles($id_files)
    {
        
        $this->id_files = $id_files;
        return $this;
    }
    
    /**
     * Gets sha256_hash
     * @return string
     */
    public function getSha256Hash()
    {
        return $this->sha256_hash;
    }
  
    /**
     * Sets sha256_hash
     * @param string $sha256_hash SHA-256 hash of the file
     * @return $this
     */
    public function setSha256Hash($sha256_hash)
    {
        
        $this->sha256_hash = $sha256_hash;
        return $this;
    }
    
    /**
     * Gets filename
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }
  
    /**
     * Sets filename
     * @param string $filename Name of the file
     * @return $this
     */
    public function setFilename($filename)
    {
        
        $this->filename = $filename;
        return $this;
    }
    
    /**
     * Gets size
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }
  
    /**
     * Sets size
     * @param int $size Size of the file
     * @return $this
     */
    public function setSize($size)
    {
        
        $this->size = $size;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Softonic\StorageApiSdk\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Softonic\StorageApiSdk\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
