<?php
/**
 * FileCdnDestination
 *
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\StorageApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Storage API
 *
 * Saves binary files in CDN providers for allowing later downloads
 *
 * OpenAPI spec version: 2.31.0
 * Contact: admin@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Softonic\StorageApiSdk\Client\Model;

use \ArrayAccess;
use \JsonSerializable;
use \Softonic\StorageApiSdk\ObjectSerializer;

/**
 * FileCdnDestination Class Doc Comment
 *
 * @category Class
 * @package  Softonic\StorageApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FileCdnDestination implements ModelInterface, ArrayAccess, JsonSerializable
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FileCdnDestination';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id_files' => 'string',
        'id_cdn_destinations' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id_files' => null,
        'id_cdn_destinations' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_files' => 'id_files',
        'id_cdn_destinations' => 'id_cdn_destinations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_files' => 'setIdFiles',
        'id_cdn_destinations' => 'setIdCdnDestinations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_files' => 'getIdFiles',
        'id_cdn_destinations' => 'getIdCdnDestinations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const ID_CDN_DESTINATIONS_PROGRAM_PRIVATE = 'program_private';
    const ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_STAGING = 'program_private_staging';
    const ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_INTEGRATION = 'program_private_integration';
    const ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_DEVELOPMENT = 'program_private_development';
    const ID_CDN_DESTINATIONS_IMAGES_PUBLIC = 'images_public';
    const ID_CDN_DESTINATIONS_IMAGES_PUBLIC_STAGING = 'images_public_staging';
    const ID_CDN_DESTINATIONS_IMAGES_PUBLIC_INTEGRATION = 'images_public_integration';
    const ID_CDN_DESTINATIONS_IMAGES_PUBLIC_DEVELOPMENT = 'images_public_development';
    const ID_CDN_DESTINATIONS_RPM_PROTECTED = 'rpm_protected';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIdCdnDestinationsAllowableValues()
    {
        return [
            self::ID_CDN_DESTINATIONS_PROGRAM_PRIVATE,
            self::ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_STAGING,
            self::ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_INTEGRATION,
            self::ID_CDN_DESTINATIONS_PROGRAM_PRIVATE_DEVELOPMENT,
            self::ID_CDN_DESTINATIONS_IMAGES_PUBLIC,
            self::ID_CDN_DESTINATIONS_IMAGES_PUBLIC_STAGING,
            self::ID_CDN_DESTINATIONS_IMAGES_PUBLIC_INTEGRATION,
            self::ID_CDN_DESTINATIONS_IMAGES_PUBLIC_DEVELOPMENT,
            self::ID_CDN_DESTINATIONS_RPM_PROTECTED,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id_files'] = isset($data['id_files']) ? $data['id_files'] : null;
        $this->container['id_cdn_destinations'] = isset($data['id_cdn_destinations']) ? $data['id_cdn_destinations'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id_files'] === null) {
            $invalidProperties[] = "'id_files' can't be null";
        }
        if ((strlen($this->container['id_files']) > 40)) {
            $invalidProperties[] = "invalid value for 'id_files', the character length must be smaller than or equal to 40.";
        }

        if ((strlen($this->container['id_files']) < 40)) {
            $invalidProperties[] = "invalid value for 'id_files', the character length must be bigger than or equal to 40.";
        }

        if ($this->container['id_cdn_destinations'] === null) {
            $invalidProperties[] = "'id_cdn_destinations' can't be null";
        }
        $allowedValues = $this->getIdCdnDestinationsAllowableValues();
        if (!in_array($this->container['id_cdn_destinations'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'id_cdn_destinations', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['id_files'] === null) {
            return false;
        }
        if ((strlen($this->container['id_files']) > 40)) {
            return false;
        }
        if ((strlen($this->container['id_files']) < 40)) {
            return false;
        }
        if ($this->container['id_cdn_destinations'] === null) {
            return false;
        }
        $allowedValues = $this->getIdCdnDestinationsAllowableValues();
        if (!in_array($this->container['id_cdn_destinations'], $allowedValues)) {
            return false;
        }
        return true;
    }


    /**
     * Gets id_files
     *
     * @return string
     */
    public function getIdFiles()
    {
        return $this->container['id_files'];
    }

    /**
     * Sets id_files
     *
     * @param string $id_files SHA-1 hash of the file
     *
     * @return $this
     */
    public function setIdFiles($id_files)
    {
        if ((strlen($id_files) > 40)) {
            throw new \InvalidArgumentException('invalid length for $id_files when calling FileCdnDestination., must be smaller than or equal to 40.');
        }
        if ((strlen($id_files) < 40)) {
            throw new \InvalidArgumentException('invalid length for $id_files when calling FileCdnDestination., must be bigger than or equal to 40.');
        }

        $this->container['id_files'] = $id_files;

        return $this;
    }

    /**
     * Gets id_cdn_destinations
     *
     * @return string
     */
    public function getIdCdnDestinations()
    {
        return $this->container['id_cdn_destinations'];
    }

    /**
     * Sets id_cdn_destinations
     *
     * @param string $id_cdn_destinations CDN destination where the file is uploaded
     *
     * @return $this
     */
    public function setIdCdnDestinations($id_cdn_destinations)
    {
        $allowedValues = $this->getIdCdnDestinationsAllowableValues();
        if (!in_array($id_cdn_destinations, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'id_cdn_destinations', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['id_cdn_destinations'] = $id_cdn_destinations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Returns data which can be serialized by json_encode()
     *
     * @return mixed[]
     */
    public function jsonSerialize()
    {
        return $this->container;
    }
}


